version: "3.8"

volumes:
  mongo_data: {}

# environment:
#   - NUMBER_OF_BIKES=1000
#   - UPDATE_INTERVAL=5  # Uppdatera varje 5 sekunder

services:

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Säkerställ att detta stämmer med backend Dockerfilen
    ports:
      - "5001:5001"  # Matcha porten som används i backend
    volumes:
      - ./backend:/app  # Monterar backend-koden
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb+srv://sagaericsson:k9zHnMrKJvWizybM@vteam.bq63y.mongodb.net/?retryWrites=true&w=majority&appName=vteam
    restart: "no"
    depends_on:
      - mongo_database

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Säkerställ att detta stämmer med frontend Dockerfilen
    ports:
      - "3000:3000"  # Port för frontend
    volumes:
      - ./frontend:/app  # Monterar frontend-koden
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://backend:5001  # För att frontend ska kunna nå backend
    restart: "no"
    depends_on:
      - backend  # Ser till att backend startas först

  # mobile-app service
  mobile-app:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./mobile-app:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://backend:5001
    restart: "no"
    depends_on:
      - backend

  # # Simulator för cyklar
  # bike_simulator:
  #   build:
  #     context: ./path-to-simulator
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend
  #   environment:
  #     - SIMULATION_SPEED=fast  # Exempel på inställning för simulatorn

  # (Valfritt) MongoDB Database
  mongo_database:
    image: mongo:latest
    container_name: mongodb
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db  # Beständigt lagringsutrymme för MongoDB

networks:
  default:
    driver: bridge
